# general order: A first then platform first, gnd/down/close first

#relay channels assigment 

A_PLATFORM_MOTOR_GND = 1
A_PLATFORM_MOTOR_LIVE = 2

A_ALIGNER_MOTOR_GND = 3
A_ALIGNER_MOTOR_LIVE = 4

B_PLATFORM_MOTOR_GND = 5
B_PLATFORM_MOTOR_LIVE = 6

B_ALIGNER_MOTOR_GND = 7
B_ALIGNER_MOTOR_LIVE = 8


#input channels assignment

#WAVESHARE_8CH_A
A_PLATFORM_DOWN_SENSOR = 1
A_PLATFORM_UP_SENSOR = 2

A_ALIGNER_CLOSE_SENSOR = 3
A_ALIGNER_OPEN_SENSOR = 4

B_PLATFORM_DOWN_SENSOR = 5
B_PLATFORM_UP_SENSOR = 6

B_ALIGNER_CLOSE_SENSOR = 7
B_ALIGNER_OPEN_SENSOR = 8

