# relay channels assigment 

LEFT_PLATFORM_MOTOR_A = 1
LEFT_PLATFORM_MOTOR_B = 2

LEFT_ALIGNER_MOTOR_A = 3
LEFT_ALIGNER_MOTOR_B = 4

RIGHT_PLATFORM_MOTOR_A = 5
RIGHT_PLATFORM_MOTOR_B = 6

RIGHT_ALIGNER_MOTOR_A = 7
RIGHT_ALIGNER_MOTOR_B = 8


#input channels assignment

LEFT_PLATFORM_DOWN_SENSOR = 1
LEFT_PLATFORM_UP_SENSOR = 2

LEFT_ALIGNER_CLOSE_SENSOR = 3
LEFT_ALIGNER_OPEN_SENSOR = 4

RIGHT_PLATFORM_DOWN_SENSOR = 5
RIGHT_PLATFORM_UP_SENSOR = 6

RIGHT_ALIGNER_CLOSE_SENSOR = 7
RIGHT_ALIGNER_OPEN_SENSOR = 8
